spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tdd?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: flamme1004!

  jpa:
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate.hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
    hibernate:
      ddl-auto: update
    generate-ddl: true